# -*- tcl -*-
#
# This file is part of GPKCS11. 
# (c) 1999-2001 TC TrustCenter GmbH 
#
# GPKCS11 is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#  
# GPKCS11 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#  
# You should have received a copy of the GNU General Public License
# along with GPKCS11; see the file COPYING.  If not, write to the Free
# Software Foundation, 59 Temple Place - Suite 330, Boston, MA 02111, USA.  
# 
# RCSID:       $Id$
# Source:      $Source$
# Last Delta:  $Date$ $Revision$ $Author$
# State:       $State$ $Locker$
# NAME:        unix.exp
# SYNOPSIS:    -
# DESCRIPTION: basic setup for unix type systems
# FILES:       -
# SEE/ALSO:    -
# AUTHOR:      lbe
# BUGS:        -
#


if ![info exists prompt] then {
    set prompt "pkcs11> "
}
proc init_pkcs11 { test } {
	#
}


#
# pkcs11_version -- extract and print the version number of calc
#
# TODO: turn this into a working fragment
proc pkcs11_version {} {
	global CSHELL
	global PKCS_LIB
	global prompt
	set version "0.6.0"
#	set tmp [exec echo "version" | $PROG]
#	regexp "$prompt *(\[^\n\]*)\n.*" $tmp tmp version
#	clone_output "[which $CSHELL] version $version\n"
	clone_output "$CSHELL version $version\n"
}
#
# pkcs11_load -- loads the program
#
proc pkcs11_load { arg } {
	#
}

#
# pkcs11_exit -- quit and cleanup
#
proc pkcs11_exit {} {
   	#
}

#
# pkcs11_start -- get pkcs11 running
#
proc pkcs11_start {} {
        #
}

pkcs11_start


