# -*- tcl -*-
#
# This file is part of GPKCS11. 
# (c) 1999-2001 TC TrustCenter GmbH 
#
# GPKCS11 is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#  
# GPKCS11 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#  
# You should have received a copy of the GNU General Public License
# along with GPKCS11; see the file COPYING.  If not, write to the Free
# Software Foundation, 59 Temple Place - Suite 330, Boston, MA 02111, USA.  
# 
# RCSID:       $Id$
# Source:      $Source$
# Last Delta:  $Date$ $Revision$ $Author$
# State:       $State$ $Locker$
# NAME:        test_decrypt.exp
# SYNOPSIS:    -
# DESCRIPTION: run tests for RSA decrypt capabilities
# FILES:       -
# SEE/ALSO:    -
# AUTHOR:      lbe
# BUGS:        -
#

set timeout 3

#
# Here are the tests
#
# Test the setting of Pins on all token of a library.
# Slots that do not have token are not touched.

#
# TODO: write a TK dialog to query the particular pins
#
set test get_modulus


#
# first get the modulus of the certificate
#
#spawn openssl x509 -inform DER -in cert_01.der -modulus -out /dev/null
#expect {
#    -re "" { pass "$test: OUT: $expect_out(2)" }
#}

set test test_decrypt
spawn gpkcs11.base/test_decrypt
expect {
    -re "foo" {
        exp_continue
    }
    
    -re "could not get function pointer list" { fail "$test: OUT: $expect_out(buffer)" }

    eof { 
	# test wether these token require login at all
	if {$no_login_reqd > 0 } {
	    pass "$test: no token requires login"   
        } else {
	    if {$invalid_pin_set == 0} {
		fail "$test: setting invalid PIN does not fail"
	    }
	    pass "$test: OUT: $expect_out(buffer)"
        }
    }
}


#
# empty test
#
#set test 
#send "(C-)\n"
#expect {
#	-re ".*$prompt$"		{ pass "$test" }
#}
    
